### ISSUE TITLE
Overlapping floating indices when pointing at the same node in Union-Find array

### ISSUE THREAD

**Issue by d4vidsha** [algorithms-in-action/algorithms-in-action.github.io#47]
In Union-Find, ‘n’ and ‘m’ are overlapping when calling union on members within same set. For example, the list of union operations `1-2,3-4,2-4,2-3` will produce the following:
![image](https://github.com/algorithms-in-action/algorithms-in-action.github.io/assets/70577814/4d4e8145-224a-42c0-a00a-7a5ecf5e2d0a)

**Comment by cate-21** [comment]
Resolved - indices now stacked.

**Comment by cate-21** [comment]
Resolved - indices are now stacked. Issue can be closed.
